### ISSUE TITLE
Im Moment überflüssige Klassen

### ISSUE THREAD

**Issue by baugid** [Kasukoi/eisverkauf#1]
Die Klassen Eis, Kugel und Warteschlange sind einfache Wrapper eines zugrunde liegenden Objektes und können theoretisch einfach entfernt werden. Es wäre aber vermutlich besser, wenn wir diese um weitere Funktionalität erweitern ( eine Kugel könnte zum Beispiel zu einem gewissen Anteil aufgegessen sein).

**Comment by Kasukoi** [comment]
Warteschlange wurde entfernt, der Rest wird wie gehabt weiter benutzt und erweitert.
